### PR TITLE
Data collection

### PR DESCRIPTION
**Pull request by sfreder**
Progress bars for delaying and for collection vibration samples are complete.  Raw data is saved to a folder named after the test selected.  Some enhancements are needed (mostly naming conventions and appearance)

### CODE REVIEW

**Comment by spencerharro** [comment]
@sfreder Is this complete or should I wait to merge?

**Comment by sfreder** [comment]
This was actually from a different branch labeled data-collection.  It is ready to merge into master.  But for practice and procedure it can be branched into develop and left there while I do a few more enhancements.  Then later I will make another pull request into master.

**Comment by sfreder** [comment]
Should work be done in branches named after issues or only in develop?

**Comment by spencerharro** [comment]
It is best to complete changes on branches off of `develop`.  As each branch is coded, continue merging `develop`'s changes into the branch to ensure the branch stays up-to-date.  Then, when the feature is complete, the merge back into `develop` should be easy.

**Comment by spencerharro** [comment]
Generally, we will make changes to `develop`, and then periodically merge `develop` into master.  Think of master like the current working app, virtually bug-free.  Like v1.0, 1.1, etc.  When `develop` merges into master, it's like incrementing the version number.  So `master` should be untouched (except by `develop`).  `develop` is where all the branching/merging of code development should happen.

**Pull request merged**
