### PR TITLE
Appearance/layout

### PR DESCRIPTION
**Pull request by beleson**
Let me know if you want me to lay in your features that are unmerged

### CODE REVIEW

**Comment by beleson** [comment]
@sfreder Can you check if this lines up with your signal process work?  I know Spencer's changes with the plot were brought in on this.

**Comment by sfreder** [comment]
I'll need a little while to do some checks.  Which one should I check first this one or #40?

**Comment by spencerharro** [comment]
@sfreder Where are you in checks with the new layout signal processing handling?  I'm downloading to my pi and planning to test a local merge.  If all checks out well, is it OK if I push changes up?

**Comment by spencerharro** [comment]
See #51 for latest.  Closing this.

**Pull request closed without merging**
