### PR TITLE
Configured poll() function to give labels "Unknown" values

### PR DESCRIPTION
**Pull request by spencerharro**
When unknown or missing data in json files

### CODE REVIEW

**Comment by spencerharro** [comment]
See #49

**Comment by sfreder** [comment]
This runs normally but I don't know how to simulate the bug that this is supposed to catch.

**Comment by spencerharro** [comment]
Try deleting the entries the the JSON data files. It should say "Unknown"
since it can't find the test preferences, save settings, etc.

**Comment by spencerharro** [comment]
Or just modify the "make" in vehicle preferences to "make1" and keep the
corresponding value whatever it was. Since app can't find "make", should
list as Unknown I think

**Comment by sfreder** [comment]
I tried something like that and it just left the value blank instead of listing "unknown"

**Comment by spencerharro** [comment]
I'm away from my computer at the moment. I'll test this again later and try
to remind myself of what I originally meant when I see the code again.

**Comment by spencerharro** [comment]
Need to work on this more before making an official merge.

**Pull request closed without merging**
