### PR TITLE
Quick enhancements

### PR DESCRIPTION
**Pull request by sfreder**
Changed some wording for labels
Changed some drop down contents
Changed some timing for Poll() updating
Improved layout of post test page

### CODE REVIEW

**Review by spencerharro — DISMISSED** [review]
@sfreder With the reduced poll time, have you tested on the RPi?  I was consistently at 100% with 1 sec polls.  When I increased it to 10 sec that brought it down to 70%.

If it checks out all right, I think its OK to merge.

**Comment by sfreder** [comment]
I will test it in a minute. To date I have not seen the processor go above 30% while running the program.  I will verify.

**Comment by spencerharro** [comment]
Might just be an anomaly with my RPi.

**Comment by sfreder** [comment]
Tested fully functional on the RPi. Processor topped out at 34%.

**Review by spencerharro — APPROVED** [review]

**Pull request merged**
