### PR TITLE
Appearance and profile / key frequency changes

### PR DESCRIPTION
**Pull request by spencerharro**
Glanced through these changes and looks like we should be able to merge.

Conflicts are really easy fixes.  I'll knock those out @beleson if you think it is a good time to merge.  We can also wait if you have other code to add in

### CODE REVIEW

**Comment by sfreder** [comment]
The frequencies only displayed on the first run.  After that they displayed zeros.  screen resolution is nice.

**Comment by spencerharro** [comment]
I think it has to do with the current test's selected speed.  @beleson set
it up as 40 or somewhere around there to make it work I think
On Wed, Apr 5, 2017 at 4:21 PM sfreder <notifications@github.com> wrote:

The frequencies only displayed on the first run. After that they displayed
zeros. screen resolution is nice.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/vibrainium-analytics/ava/pull/82#issuecomment-291985101>,
or mute the thread

**Comment by spencerharro** [comment]
Good point, forgot to test that. I have to rewrite the file-finding code.
Shouldn't be too bad

**Comment by sfreder** [comment]
if you want you can do the pull first and make corrections later.

**Comment by spencerharro** [comment]
No, I better get this working first

**Comment by spencerharro** [comment]
I just confirmed with @beleson about the zeros: "if the saved file has it at zero for gear or speed it zeros it out"

**Comment by sfreder** [comment]
ran with different speeds. still got zeros

**Review by sfreder — CHANGES_REQUESTED** [review]
Works great the first run through.  Then throws so many errors it won't restart.  Problems with handling the info from the new vehicle page I think.

**Comment by spencerharro** [comment]
@sfreder is this the error you see?  When I run a test and then go to the plot page and select data to plot, the app seems to recover and update the plot.
screen shot 2017-04-06 at 8 47 21 pm

**Comment by sfreder** [comment]
The errors were much worse than that. trying to divide a string by a float and things like that.  Bringing it up to date with develop may have fixed it. I will check on it now.

**Comment by sfreder** [comment]
The python exceptions are gone but it is buggy and prints at lot of debug messages.

For instance when I change the selected test in the drop down the plot does not always update and I get this message printed out:
ERROR: Baseline + Data plot save unsuccessful
--------------------------
ERROR: Plot update failed.
ERROR: Data did not load successfully

Then it repeats this message every second:
-------------------
ERROR: Animate function has error(s)
ERROR: Data did not load successfully

**Comment by sfreder** [comment]
Sorry about the bold. It didn't show up that way in my comment window

**Comment by spencerharro** [comment]
Here's one possible trail to follow: Data did not load successfully... that means that the np.loadtxt() function that turns the fft file into an array does not have correct data to work with.

**Comment by spencerharro** [comment]
Maybe a better idea for starters.  Let's put some dummy data in DataPlotFile.txt.  Possibly that got corrupted (hence Animate function failed)

Actually, you said the plot at least _sometimes_ updates.  So this probably won't help

**Comment by spencerharro** [comment]
Can you make a branch and push up exactly the files you see now (just `git add .` on that new branch).  I'll take a look from my end

**Comment by sfreder** [comment]
if I did it right you will find my files in this new branch:  Brian/profile_and_key_freqs_debug

**Comment by spencerharro** [comment]
I see the branch.  Fetching now

**Comment by spencerharro** [comment]
First error I can see: ValueError: could not convert string to float:, points to reverse_Gear = float(reverse_Gear_str)

Reason: "reverse_Gear" in the current vehicle profile is just "", so nothing to convert

**Comment by spencerharro** [comment]
@sfreder selected_vehicle.json was missing some essential parameters (reverse gear, powersteer, tension).  I think my latest push on the debug branch fixes the bugs that prevented app launch

**Review by sfreder — APPROVED** [review]

**Comment by sfreder** [comment]
This is ready to merge.

**Pull request merged**
