### PR TITLE
Feature/integrate plots

### PR DESCRIPTION
**Pull request by spencerharro**
Merged plot page code from old UI

### CODE REVIEW

**Comment by sfreder** [comment]
Looks good to me. I'm not sure if you wanted me to do the merge or not

**Comment by spencerharro** [comment]
Go ahead.  Generally a good idea for someone other than code author to make the change.  You could also do a `git fetch && git checkout Feature/integrate_plots` to see the update in action to confirm from your end.

**Comment by sfreder** [comment]
I found that you can review the code here by clicking on the commits and files changed tabs.

**Comment by sfreder** [comment]
Do we want to get in the habit of deleting branches when we merge?

**Comment by spencerharro** [comment]
Deleting sounds good.

**Pull request merged**
