### PR TITLE
Brian/profile and key freqs debug

### PR DESCRIPTION
**Pull request by spencerharro**
#82

### CODE REVIEW

**Comment by sfreder** [comment]
I'm thinking stop trying to get this merge to work and start a new branch from develop and then build the desired features on to there.

**Comment by spencerharro** [comment]
I am looking through the diff between the new branch and develop.  Appears that some profile variables got renamed in the new update, and those changes are not reflected in other pages.  I think this is what is causing the merge challenges

**Comment by spencerharro** [comment]
This seems to be testing better now.  I merged in the latest develop changes.

**Comment by sfreder** [comment]
The problem was in data validation.  I will have this cleaned up and ready to go this evening.

**Review by sfreder — APPROVED** [review]
Made lots of changes to the plot page to make key frequencies work. I will merge this now.

**Pull request merged**
