### PR TITLE
Compare/bug fix

### PR DESCRIPTION
**Pull request by sfreder**
Comparison has been updated.  Vibration profiles are now compared only by the frequency of the peaks and not magnitude.  This has been field tested and the results are good.  

AC has been removed from the post test questions.  Idle-AC-on is now considered a known trouble condition.  

The latest data from testing on my car is in this version.  It is the only test data that is currently valid.

### CODE REVIEW

**Comment by sfreder** [comment]
Correction. I accidentally deleted all of my most recent tests for my car.  I will begin re-establishing baselines this week.

**Comment by sfreder** [comment]
I have a few more changes to make before this should be merged

**Comment by sfreder** [comment]
I have added new vehicle data and updated the MKR file.

**Review by spencerharro — APPROVED** [review]
Works great on my MKR and ava app.  Thanks also for the fresh data

**Pull request merged**
