### PR TITLE
Feature/plot from tests

### PR DESCRIPTION
**Pull request by beleson**

### CODE REVIEW

**Comment by sfreder** [comment]
@beleson  In an earlier merge I made changes to the directory handling by making use of a new file (directory.json).  The primary reason for this was so that I could make one quick change on the home page and run the code on my laptop instead of on the RPi.  Do you mind if I alter your code so that this still functions before we merge?

**Comment by beleson** [comment]
Go for it.  As long as we are all on the same page we should be good.




On Mar 16, 2017 4:04 PM, "sfreder" <notifications@github.com> wrote:

@beleson <https://github.com/beleson> In an earlier merge I made changes to
the directory handling by making use of a new file (directory.json). The
primary reason for this was so that I could make one quick change on the
home page and run the code on my laptop instead of on the RPi. Do you mind
if I alter your code so that this still functions before we merge?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vibrainium-analytics/ava/pull/40#issuecomment-287174991>,
or mute the thread

**Comment by sfreder** [comment]
I'll let you know when my changes are ready to be checked on your end.

**Comment by sfreder** [comment]
One of the things we should probably do is stay in the /home/pi/ava/ directory as much as possible and avoid using os.chdir.  We want the ability to access other directories but we want to stay at home.

**Comment by sfreder** [comment]
Merging this to my previous versions is proving intensive. I am going to make a branch off of this one and work on it today.  Hopefully I have time to get it done.  then you can check my branch and start merging.

**Comment by spencerharro** [comment]
@sfreder I have a few minutes to talk about the merge challenge if that would help.  Code from this branch is still fresh in my mind.

**Comment by beleson** [comment]
I can too.  Let me know via hangouts if want to Skype about the merge

**Comment by spencerharro** [comment]
Folded into #51

**Pull request closed without merging**
