### PR TITLE
Integrate data analysis

### PR DESCRIPTION
**Pull request by sfreder**
This branch is finally ready to merge. Signal acquisition and signal processing works. Creates 4 files in one folder. Folder is the name of the test ex: Steve-Toyota-Corolla/Baseline-Idle/<files>

### CODE REVIEW

**Comment by spencerharro** [comment]
I am unable to test from my end.  Either @beleson or @jdgeyer9 would be better for the merge.

**Comment by sfreder** [comment]
I may be able to add a file that has the necessary raw data so that you can simulate it after running with 0 delay and 0 test duration.  I will get back to this a little later.

**Review by spencerharro — APPROVED** [review]
Looked through changes and does not affect any of the files I'm working on.  Since it works on your end, I'm good with you merging @sfreder

**Comment by sfreder** [comment]
I am adding a simulation feature that can run without the MKR if you enter 0 for delay time and 0 for test duration.

**Pull request closed without merging**
